CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

CONFIG_BT=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_OBSERVER=y

CONFIG_SENSOR=y
CONFIG_I2C=y

CONFIG_PM=y
CONFIG_PM_DEVICE=y

CONFIG_WATCHDOG=y
